### ISSUE TITLE
Serverless blog costs

### ISSUE THREAD

**Issue by edmorley** [sjevs/blog.jevsejev.io#2]
I've spotted a miscalculation on:
http://blog.jevsejev.io/2016/05/17/aws-serverless-blog-costs/

The Route 53 standard DNS queries would actually be free, since you'd use an alias to S3, which are free:

> Queries to Alias records that are mapped to Elastic Load Balancers, Amazon CloudFront distributions, AWS Elastic Beanstalk environments, and Amazon S3 website buckets are free. Alias records can be created for all query types: standard queries, latency-based routing queries, and geo queries. These queries are listed as “Intra-AWS-DNS-Queries”, “Intra-AWS-LBR-Queries”, or “Intra-AWS-Geo-Queries” on the Amazon Route 53 usage report.

(From: https://aws.amazon.com/route53/pricing/)

Also worth noting that to reduce the overall cost you could put Cloudflare (free plan) in front of S3, which would reduce S3 requests+data significantly (plus mean you could skip Route53 entirely, saving the hosted zone cost too).

Anyway thank you for the post :-)

**Comment by sjevs** [comment]
Hi, 

thanks a lot for the input. Yes, it seems you are right. But AWS still charges for it.

![screen shot 2017-04-20 at 13 31 15](https://cloud.githubusercontent.com/assets/1146115/25228695/afc2156a-25cd-11e7-8e37-c369ecab2a47.png)

Probably, that these occur the DNS requests not directly to blog website, but to main domain. Its really weird. Probably bots or other noise from the internet which is fetching the DNS data.

I will add a short update to it, since my blog costs fits the predicted costs.

Thanks!

**Comment by edmorley** [comment]
Perhaps because jevsejev.io currently doesn't have DNS configured correctly?
```
$ nslookup jevsejev.io
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
*** Can't find jevsejev.io: No answer
```

If it were pointed at an S3 bucket which redirected, then presumably it would still be free.

**Comment by sjevs** [comment]
I just did fix the main domain as you pointed out.
